name: 01 Push to Dockerhub

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

env:
  APP_NAME: forntend_dockerhub
  SERVICE: frontend
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}/-${{ env.SERVICE }}/${{env.BRANCH_NAME}}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: ${{ env.SERVICE }}
          dockerfile: ${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
