name: 01 Push to Dockerhub

on:
  push:
    branches:
      #- master
      - Test
    paths:
      - 'CICD/frontend/**'

env:
  APP_NAME: forntend_dockerhub
  SERVICE: frontend

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}-${{ env.SERVICE }}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: ${{ env.SERVICE }}
          dockerfile: ${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
