name: 02 Build & deploy my-app-backend image

on:
  workflow_run:
    workflows:
      - GitHub-Demo
    branches:
      -dev
      -master
    types:
      -completed

env:
  APP_NAME: backend_dockerhub # This value was modified by the initial-setup python script
  SERVICE: backend
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}-${{ env.SERVICE }}-${{env.BRANCH_NAME}}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: ${{ env.SERVICE }}
          dockerfile: ${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
